### ISSUE TITLE
Names of form "sp. n." have "sp" at end

### ISSUE THREAD

**Issue by rdmpage** [GlobalNamesArchitecture/gnrd#10]
Names that are part of a string such as _Rhypholophus dufouri_ sp. n. get interpreted as "Rhypholophus dufouri sp". The "sp" is clearly extraneous, can this be pruned off? At the moment I have to do this internally so that I can match names to pages, e.g. http://bionames.org/names/cluster/1049906

To see a live example of this bug, see http://gnrd.globalnames.org/name_finder.html?token=3rkep8uekg where I've looked for names in the PDF http://retro.seals.ch/cntmng?pid=seg-001:1993:66::693

**Comment by dimus** [comment]
The problem was in NetiNeti. I added "sp" to blacklist, should be fixed now
