### ISSUE TITLE
Hippopotamus

### ISSUE THREAD

**Issue by dshorthouse** [GlobalNamesArchitecture/gnrd#11]
From a comment by @stralion in Disqus comment on website:
Look at this paper: http://rsos.royalsocietypublishing.org/content/2/9/150156
The name "Hippopotamus amphibius" occurs twice, and "H. amphibius" occurs twice.
When given the URL, GNRD finds "H. amphibius" but not "Hippopotamus amphibius". When given the PDF, GNRD does not find either one.

**Comment by dimus** [comment]
There is  a related [issue](https://github.com/phylotastic/phylotastic-portal/issues/157). I want to fix "grey" list handling and make it more "intelligent" in new version of name-finding engine which will replace TF and NetiNeti
