### ISSUE TITLE
Token URL returns same results as search URL

### ISSUE THREAD

**Issue by themerekat** [GlobalNamesArchitecture/gnrd#12]
When a poll the token URL that I receive after performing a search, I get the same result as the search URL.

For example, using this token URL: http://gnrd.globalnames.org/name_finder.xml?token=6jgv9mqdq8

just returns:

![image](https://user-images.githubusercontent.com/16688784/26883442-3520be1a-4b6b-11e7-8e5b-4db4ddd53d4e.png)

but I need a result that contains a scientific name, like so:

![image](https://user-images.githubusercontent.com/16688784/26883518-5f5a5be6-4b6b-11e7-9d32-6afa5d665274.png)

I haven't had this issue in the past. Any idea why its not working now? Thanks!

**Comment by dimus** [comment]
Do you still have this problem? I cannot reproduce it

**Comment by kds15e** [comment]
Yes, I am getting the same problem, for example, with the following token URL: http://gnrd.globalnames.org/name_finder.xml?token=7hs2lloo03

This is the result:
![image](https://user-images.githubusercontent.com/16688784/27282608-b9c4cd08-54be-11e7-9828-bc3229fd7dd5.png)

**Comment by themerekat** [comment]
Trying just now, I found that it was working again. Odd! Thanks for checking in.
