### ISSUE TITLE
Rake aborting

### ISSUE THREAD

**Issue by dashish333** [GlobalNamesArchitecture/gnrd#27]
Followed the steps mentioned, but eventually getting the following error:
Also, config.example.json is missing from the production branch, hence copied the content form 17-gnfinder-only

`Starting gnrd_redis_1 ... done
Starting gnrd_gnf_1   ... done
Starting gnrd_pg_1    ... done
rake aborted!
PG::ConnectionBad: could not translate host name "pg" to address: No address associated with hostname
/var/lib/gems/2.6.0/gems/pg-1.1.4/lib/pg.rb:56:in `initialize'
/var/lib/gems/2.6.0/gems/pg-1.1.4/lib/pg.rb:56:in `new'
/var/lib/gems/2.6.0/gems/pg-1.1.4/lib/pg.rb:56:in `connect'
/var/lib/gems/2.6.0/gems/activerecord-5.2.4/lib/active_record/connection_adapters/postgresql_adapter.rb:692:in `connect'
/var/lib/gems/2.6.0/gems/activerecord-5.2.4/lib/active_record/connection_adapters/postgresql_adapter.rb:223:in `initialize'
/var/lib/gems/2.6.0/gems/activerecord-5.2.4/lib/active_record/connection_adapters/postgresql_adapter.rb:48:in `new'
/var/lib/gems/2.6.0/gems/activerecord-5.2.4/lib/active_record/connection_adapters/postgresql_adapter.rb:48:in `postgresql_connection'
/var/lib/gems/2.6.0/gems/activerecord-5.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:830:in `new_connection'
/var/lib/gems/2.6.0/gems/activerecord-5.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:874:in `checkout_new_connection'
/var/lib/gems/2.6.0/gems/activerecord-5.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:853:in `try_to_checkout_new_connection'
/var/lib/gems/2.6.0/gems/activerecord-5.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:814:in `acquire_connection'
/var/lib/gems/2.6.0/gems/activerecord-5.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:538:in `checkout'
/var/lib/gems/2.6.0/gems/activerecord-5.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:382:in `connection'
/var/lib/gems/2.6.0/gems/activerecord-5.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:1033:in `retrieve_connection'
/var/lib/gems/2.6.0/gems/activerecord-5.2.4/lib/active_record/connection_handling.rb:118:in `retrieve_connection'
/var/lib/gems/2.6.0/gems/activerecord-5.2.4/lib/active_record/connection_handling.rb:90:in `connection'
/var/lib/gems/2.6.0/gems/activerecord-5.2.4/lib/active_record/tasks/database_tasks.rb:57:in `check_protected_environments!'
/var/lib/gems/2.6.0/gems/activerecord-5.2.4/lib/active_record/railties/databases.rake:13:in `block (2 levels) in <top (required)>'
/var/lib/gems/2.6.0/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:reset => db:drop => db:check_protected_environments
`

**Comment by dimus** [comment]
Do you know that you can use https://github.com/gnames/gnfinder directly?

**Comment by dashish333** [comment]
Yes, came across the gnfinder binary executable. But my use-case would involve pdfs and URLs beside the text. It's my assumption the above wouldn't fulfil my requirement. Please clarify me, if my understanding is partial.

**Comment by dashish333** [comment]
Need urgent help on this.

**Comment by dimus** [comment]
Would be hard to quide you by exchanging comments here, how about chatting?

https://gitter.im/GlobalNamesArchitecture/GlobalNames

**Comment by dashish333** [comment]
Resolved
