### ISSUE TITLE
Text-based PDFs get OCR'd

### ISSUE THREAD

**Issue by dshorthouse** [GlobalNamesArchitecture/gnrd#3]
https://github.com/GlobalNamesArchitecture/gnrd/blob/master/models/name_finder.rb#L309 indicates that all PDF files get OCR'd. While this is good for image-based PDFs, this is not good for text-based PDFs; the result is poorer name-finding than otherwise could be. We need a mechanism to determine if a PDF is text-based vs image-based and set the ocr: true/false flag appropriately.

**Comment by dshorthouse** [comment]
Something like this might work with the pdf-reader gem:

``` ruby
      if file_type.match /PDF/
        opts.merge!({ :pages => 'all' })
        reader = PDF::Reader.new(self.file_path)
        opts.merge!({ :ocr => false }) if !reader.pages[0].text.empty?
      end
```

**Comment by dimus** [comment]
Sounds good man, I'll keep it in mind when im back to GNRD

**Comment by dimus** [comment]
Docsplit seem to work correctly with default settings. Images in PDF get OCRed, text PDF is not. Checking using new code v0.8.3 located at http://finder.globalnames.org

**Comment by dshorthouse** [comment]
Might be an edge case, but earlier when I first discovered the issue, I had a PDF whose first page was an image and remaining pages were text. Even though p2+ were text, they were all treated as images, tiffs produced, and then OCR'd.

**Comment by dimus** [comment]
We did have {ocr: true} in original code, so that would be an expected behavior. I'll make a file like this and see how it behaves then (if you still have yours, let me know ;)
