### ISSUE TITLE
GNRD is identifying people's names in text citation

### ISSUE THREAD

**Issue by diatomsRcool** [GlobalNamesArchitecture/gnrd#31]
Refer to GNRD Dryad project:
| Name | Package |
| ------- | -------- |
| Elsa | 78 |
| Paula | 202 |
| Gabriella | 792 |
| Lisa | 792 |
| Alfaro | 170 |
| Cullen | 202 |
| Plana | 340 |
| Idris | 340 |
| Barbosa | 346 |
| Rana | 346 |
| Garreta | 802 |
| Cano | 802 |
| Yamada | 825 |
| Barbosa | 890 |
| Theron | 917|
| Berta | 923 |
| Moreno | 949 |
| Moreno | 2 |
| Vizcaino | 39|

More names (I can provide the data package number if needed)

- Talavera
- Crosa
- Pinon
- Graus
- Caterino
- Casas
- Ades
- Narum
- Ikeda
- Camara
- Abila
- Simo
- Fraga
- Verma
- Moreno
- Vitalis
- Imber
- Luca
- Ziminia
- Lara
- Darda canica
- Luca
- Kukalova
- Leis
- Mossman
- Vitalis
- Fontanella
- Nason
- Ferna
- Beleza
- Mona
- Pereira
- Talavera
- Luzuriaga
- Vila
- Mona
- Tella
- Ferna
- Gaeta
- Civetta
- Ojeda
- Piras
- Oyama
- Narum
- Vitalis
- Colla
- Moreno
- Narita
- Roche
- Gaeta
- Alfaro
- Barbosa
- Tanada
- Sasa
- Carmona
- Momot
- Quesada
- Moya
- Tarka
- Tobias
- Pereira
- Narum
- Rubini
- Nason
- Tella
- Narum
- Talavera
- Egea
- Vila
- Gregorius
- Moreno
- Vila
- Vitalis
- Tsukada
- Gregorius

**Comment by dimus** [comment]
It happens because these words are also valid names. 

For example https://verifier.globalnames.org/api/v1/verifications/Tsukada

The same problem happens with some geographical entities like `America` for example.

To avoid false positives we need to study contexts and apply machine learning techniques I guess.

**Comment by dimus** [comment]
Added https://github.com/gnames/gnfinder/issues/62 for name finding algorithm. If I add the names to grey dictionary, it should help to hide such stand-alone names from results.
