### ISSUE TITLE
GNRD is identifying place names as taxa

### ISSUE THREAD

**Issue by diatomsRcool** [GlobalNamesArchitecture/gnrd#32]
Below are false positives that are place names. I have included the actual text string, if that helps. We might be able to use that to differentiate places from taxa.

data package ID | name | error type | text string
-- | -- | -- | -- 
45 | Balclutha | false positive |  
45 | Ringaringa | false positive |  
153 | Visaya | false positive |  
215 | Tagua | false positive |  
215 | Bogota | false positive |  
225 | Mona | false positive | Mona Passage
252 | Gora | false positive | Mokra Gora, Serbia
274 | Tulsa | false positive | Tulsa, OK, USA
297 | Tulsa | false positive | Tulsa Zoo
301 | Manoa | false positive | Manoa, Honolulu
304 | Cabrera | false positive |  
304 | Catarina | false positive |  
304 | Casas | false positive |  
317 | Rungwe-kitulo kipunji | false positive | Mt Rungwe-Kitulo
323 | Punta | false positive | Punta Arenas, Chile
323 | Noumea | false positive | Noumea, New Caledonia
323 | Moorea | false positive | Papetoai Moorea, French Polynesia
350 | Cassine | false positive |  
356 | Yulong | false positive | Mingyin, Yulong Co., YN
356 | Gonga | false positive | Gonga Shan
422 | Beringia | false positive |  
448 | Balsas | false positive | Balsas River Valley
481 | Punta | false positive | Punta Prieta
481 | Rosalia | false positive | Santa Rosalia
487 | Malleco | false positive | Chile: Malleco
536 | Nicola | false positive |  
536 | Ucla | false positive | UCLA
536 | Uinta | false positive | Uinta Mountains
536 | Castilla | false positive | La Rosa de Castilla
536 | Valpara | false positive |  
536 | Chiricahua | false positive | Chiricahua Mountains
536 | Rita | false positive | Rancho Santa Rita
536 | Atoyac | false positive | Sierra de Atoyac
536 | Potos | false positive |  
536 | Casas | false positive |  
595 | Emilia | false positive | Reggio Emilia, Italy
645 | Taita | false positive | Taita Hills
667 | Vasco | false positive |  
667 | Castilla | false positive |  
667 | Rioja | false positive |  
831 | Brea | false positive | Brea, CA
868 | Wakulla | false positive | Wakulla Springs
874 | Yarra | false positive | Yarra Ranges National Park
923 | Ucla | false positive | UCLA
923 | Brea | false positive | Rancho La Brea, California
933 | Kahua | false positive | Kahua Ranch
933 | Lana | false positive | Lana'i
933 | Kaala | false positive | Mt. Kaala
946 | Gorgora | false positive | Gorgora, Ethiopia
946 | Harena | false positive | Harena forest
966 | Roche | false positive | Roche, Switzerland
966 | Eungella | false positive |  
999 | Alexandrina | false positive | Lake Alexandrina
1038 | Pesotum | false positive | Pesotum, IL
1038 | Mariposa | false positive | Mariposa, CA
1076 | Pima | false positive | USA, Arizona, Pima
1076 | Pina | false positive | Pina, Co
1097 | Paria | false positive | Paria river
1097 | Yarra | false positive | Yarra river
1142 | Atacama | false positive | Atacama desert
1158 | Punta | false positive | Punta Galeras
1185 | Tyson | false positive | Tyson Research Center
1207 | Valdivia | false positive | Valdivia, Chile
1207 | Angra | false positive | Angra do Heroismo, Portugal
1207 | Tulsa | false positive | Tulsa, OK, USA
1257 | Caura | false positive | Rio Caura
1257 | Lema | false positive | Sierra de Lema
1257 | Roraima | false positive | Roraima-Rupununi savanna
1277 | Cirella | false negative | population of Cirella
1326 | Knysna | false positive | Knysna Estuary
1332 | Roraima | false positive |  
1359 | Atacama | false positive | Atacama Desert
1359 | Caleta | false positive | Caleta El Cobre
1359 | Campana | false positive | Cerro La Campana range
1381 | Cuernavaca | false positive | Cuernavaca Mexico
1392 | Tapajos | false positive | Tapajos River
333 | Cuernavaca | false positive |  
333 | Pima | false positive |  
1371 | Sanda | false positive | swedish aw
1371 | Astra | false positive | swedish aw
1332 | Amapa | false positive | Brazilian states of Amapa | location
1392 | Maderia | false positive |   | misspelled place name
198 | Ballena | false positive |   | name of location
340 | Manengouba | false positive | Mt. Manengouba | name of mountain, but also specific epithet
137 | Osaka | false positive |   | name of place

**Comment by dimus** [comment]
Thanks @diatomsRcool ! I am adding a ticket to gnfinder

https://github.com/gnames/gnfinder/issues/63
