### ISSUE TITLE
GNRD is grabbing acronyms as taxon names

### ISSUE THREAD

**Issue by diatomsRcool** [GlobalNamesArchitecture/gnrd#34]
data package | name | error type | text string | notes
-- | -- | -- | -- | --
39 | Ancova | false positive |   | acronym
39 | Rapa | false positive |   | acronym
39 | Ucla | false positive |   | acronym
39 | Ucla collection | false positive | UCLA collection | acronym
1359 | Awsa lineages | false positive | arid western South American (AWSA) | acronym
202 | Ancova | false positive |   | acronym for statistical text
182 | Acia | false positive |   | acronym in text citation
1420 | Inia | false positive |   | institute acronym
313 | Ancova | false positive | (ANCOVA) | statistical test
483 | Ancova | false positive |   | statistical test
868 | Ancova | false positive | ANCOVA | statistical test
939 | Mancova revealed | false positive | The MANCOVA revealed | statistical test
962 | Ancova | false positive | ANCOVA | statistical test
1031 | Ancova | false positive | ANCOVA | statistical test
1109 | Ancova | false positive |   | statistical test
1185 | Ancova | false positive | ANCOVA | statistical test

**Comment by dimus** [comment]
Sounds like these belong for checking with https://github.com/gnames/gnfinder/issues/64

**Comment by dimus** [comment]
Adding to dictionaries:
reject:
awsa
mancova

grey:
ancova
acia
rapa
ucla
inia

**Comment by dimus** [comment]
fixed in gnfinder v0.12.0
