### ISSUE TITLE
GNRD having trouble with tables

### ISSUE THREAD

**Issue by diatomsRcool** [GlobalNamesArchitecture/gnrd#35]
To some degree, I'm assuming these problems are caused by the name being in a table. I can't be sure.

data package ID | name | error type | text string | notes
-- | -- | -- | -- | --
536 | A. unicolor unicolor | false positive |   | a wierd table row issue
536 | A. griscomi griscomi | false positive |   | a wierd table row issue
317 | Papio papio ursinus | false positive |   | combined two names across table column   headers
317 | Papio cynocephalus anubis | false positive |   | combined two names across table column headers
379 | Hemideina crassidens | false negative |   | genus and specific epithet are separate by columns in table (sideways)
379 | Prosphena scudderi | false negative |   | genus and specific epithet are separate by columns in table (sideways)
379 | Prosarthria teretrirostris | false negative |   | genus and specific epithet are separate by columns in table (sideways)
379 | Tettigonia viridissima | false negative |   | genus and specific epithet are separate by columns in table (sideways)
379 | Cylindraustralia kochii | false negative |   | genus and specific epithet are separate by columns in table (sideways)
379 | Glauia terrea | false negative |   | genus and specific epithet are separate by columns in table (sideways)
379 | Agathemera crassa | false negative |   | genus and specific epithet are separate by columns in table (sideways)
379 | Cyphoderris monstrosus | false negative |   | genus and specific epithet are separate by columns in table (sideways)
379 | Acrida turrita | false negative |   | genus and specific epithet are separate by columns in table (sideways)
379 | Neotridactylus australis | false negative |   | genus and specific epithet are separate by columns in table (sideways)
379 | Grylloblatta rothi | false negative |   | genus and specific epithet are separate by columsn in table (sideways)
379 | Euschmidtia cruciformis | false negative |   | genus and specific epithet are separate by columsn in table (sideways)
379 | Phyllium bioculatum | false negative |   | genus and specific epithet are separate by columsn in table (sideways)
379 | Gromphadorhina portentosa | false negative |   | genus and specific epithet are separate by columsn in table (sideways)
379 | Oedipoda coerulescens | false negative |   | genus and specific epithet are separate by columsn in table (sideways)
379 | Paratettix cucullatus | false negative |   | genus and specific epithet are separate by columsn in table (sideways)
379 | Homeomastax dentata | false negative |   | genus and specific epithet are separate by columsn in table (sideways)
379 | Ruspolia nitidula | false negative |   | genus and specific epithet are separate by columsn in table (sideways)
379 | Gomphocerippus rufus | false negative |   | genus and specific epithet are separate by columsn in table (sideways)
379 | Bullacris membracioides | false negative |   | genus and specific epithet are separate by columsn in table (sideways)
379 | Stiphra robusta | false negative |   | genus and specific epithet are separate by columsn in table (sideways)
379 | Pneumora inanis | false negative |   | genus and specific epithet are separate by columsn in table (sideways)
379 | Pyrgomorpha conica | false negative |   | genus and specific epithet are separate by columsn in table (sideways)
127 | T. californium | false negative |   | in table
137 | D.m. | false negative |   | in table
137 | C.i. | false negative |   | in table
137 | H.s. | false negative |   | in table
137 | B.f. | false negative |   | in table
137 | S.p. | false negative |   | in table
137 | P.m. | false negative |   | in table
137 | O.d. | false negative |   | in table
241 | M. coryphaeus | false negative |   | in table
241 | Ictitherinae | false negative |   | in table
252 | L. g. artvinensis | false negative |   | in table
258 | Dicentra | false negative |   | in table
297 | Otolemur garnetti | false negative |   | in table
297 | Saimiri scieureus | false negative |   | in table
329 | Eichhornia meyeri | false negative |   | in table
383 | Loxodonta | false negative |   | in table
383 | Hyrax | false negative | Hyrax + horse | in table
383 | Dugong | false negative |   | in table
383 | Bos | false negative |   | in table
383 | Mus | false negative |   | in table
383 | Homo | false negative |   | in table
405 | Trabeculus flemingi | false negative |   | in table
405 | H. falsus pacificus | false negative |   | in table
438 | D. iki | false negative |   | in table
487 | Ips | false negative |   | in table
487 | Trypodendron | false negative |   | in table
487 | Curculio | false negative |   | in table
487 | Bronchus | false negative |   | in table
487 | Tanysphyrus | false negative |   | in table
563 | Pinna | false negative |   | in table
563 | Scaphoda | false negative |   | in table
645 | Pica pica | false negative |   | in table
684 | L. elongatus | false negative |   | in table
684 | L. attenuatus | false negative |   | in table
684 | N. cunningtoni | false negative |   | in table
684 | L. signatus | false negative |   | in table
684 | N. modestus | false negative |   | in table
684 | J. ornatus | false negative |   | in table
684 | N. calliurus | false negative |   | in table
684 | N. tetracanthus | false negative |   | in table
684 | N. brevis | false negative |   | in table
684 | N. savoryi | false negative |   | in table
684 | N. moorii | false negative |   | in table
684 | L. profundicola | false negative |   | in table
684 | A. calvus | false negative |   | in table
684 | L. ornatipinnis | false negative |   | in table
743 | Sellaphora cf. minima | false negative |   | in table
743 | Aulacoseira granulata v. angustissima | false negative |   | in table
743 | Cymbella ventricosa/turgida | false negative |   | in table
923 | Homotheriini | false negative |   | in table
1011 | Araucaria | false negative |   | in table
1011 | Geranium | false negative |   | in table
1011 | Acacia | false negative |   | in table
1011 | Rhododendron | false negative |   | in table
1011 | Sphagnum | false negative |   | in table
1011 | Ginko | false negative |   | in table
1011 | Sequoia | false negative |   | in table
1011 | Trifolium | false negative |   | in table
1011 | Pelargonium | false negative |   | in table
1011 | Oenotherna | false negative |   | in table
1011 | Brassica | false negative |   | in table
1011 | Nicotiana | false negative |   | in table
51 | Brachymeles cf. bonitae | false negative |   | in table
51 | B. cf. bonitae | false negative |   | in table
51 | B. cf. samarensis | false negative |   | in table
51 | Brachymeles cf. samarensis | false negative |   | in table
100 | Ectyoplasia ferax | false negative |   | in table
645 | Malurus cyaneuss | false negative |   | in table - a misspelling
100 | Neurospora crass | false negative |   | in table - fix in annotation file
385 | Firmicutes | false negative |   | in table - is it this or Firmicutes bacteria?
385 | Firmicutes bacteria | false positive |   | in table - is it this or just Firmicutes?
379 | Panchloridae | false negative |   | in table (sideways) ? not sure why GNRD missed this
684 | L. lemairii | false negative |   | in table and in text with punctuation
743 | Amphora | false negative |   | in table and in text without italics
379 | Acridomorphoidea | false negative |   | in table caption (sideways) ? not sure why GNRD missed this
219 | Helianthus | false negative |   | in table column headers
1349 | Disa ferruginea | false negative |   | in table on two rows
1349 | Disa ophrydea ferruginea | false positive |   | in table on two rows
1349 | Disa | false positive |   | in table on two rows
1463 | Lerista bougainvilli | false negative |   | in table on two rows
405 | Ea. minor | false negative |   | in table sideways
405 | Pe. marina | false negative |   | in table sideways
405 | M. antipodes | false negative |   | in table sideways
457 | Oxethira | false negative |   | in table sideways
457 | Marillia | false negative |   | in table sideways
457 | Brysopterix | false negative |   | in table sideways
457 | Catocola | false negative |   | in table sideways
487 | Anthonominae | false negative |   | in table sideways
487 | Otidocephalinae | false negative |   | in table sideways
487 | Camarotinae | false negative |   | in table sideways
487 | Pseudomopsis inflata | false negative |   | in table sideways
487 | Stenopelmus rufinasus | false negative |   | in table sideways
487 | Myrmex floridanus | false negative |   | in table sideways
487 | Mecininae | false negative |   | in table sideways
536 | A. griscomi | false negative |   | in table sideways
1257 | Euphonia rufiventris | false negative |   | in table sideways
1257 | Hylophilus hypoxanthus | false negative |   | in table sideways
1257 | Xiphorhynchus guttatus polystictus | false negative |   | in table sideways
1257 | L. a. duidae | false negative |   | in table sideways
1257 | A. i. badius | false negative |   | in table sideways
1257 | A. r. venezuelanus | false negative |   | in table sideways
1257 | Automolus infuscatus cervicalis | false negative |   | in table sideways
1257 | Automolus rubiginosus obscurus | false negative |   | in table sideways
1257 | Brotogeris chrysoptera | false negative |   | in table sideways
1257 | Brotogeris cyanoptera | false negative |   | in table sideways
1257 | C. c. cinerascens | false negative |   | in table sideways
1257 | C. e. jumanus | false negative |   | in table sideways
1257 | C. l. intermedius | false negative |   | in table sideways
1257 | C. t. occidentalis | false negative |   | in table sideways
1257 | C. t. tyrannina | false negative |   | in table sideways
1257 | Capito auratus | false negative |   | in table sideways
1257 | Capito niger | false negative |   | in table sideways
1257 | Celeus elegans elegans | false negative |   | in table sideways
1257 | Celeus grammicus | false negative |   | in table sideways
1257 | Celeus torquatus torquatus | false negative |   | in table sideways
1257 | Celeus undatus | false negative |   | in table sideways
1257 | Cercomacra cinerascens immaculata | false negative |   | in table sideways
1257 | Cercomacra tyrannina saturatior | false negative |   | in table sideways
1257 | Cymbilaimus lineatus lineatus | false negative |   | in table sideways
1257 | D. c. radiolatus | false negative |   | in table sideways
1257 | D. f. phaeochroa | false negative |   | in table sideways
1257 | D. m. bartletti | false negative |   | in table sideways
1257 | D. p. validus | false negative |   | in table sideways
1257 | Dendrocincla fuliginosa fuliginosa | false negative |   | in table sideways
1257 | Dendrocincla merula merula | false negative |   | in table sideways
1257 | Dendrocolaptes certhia certhia | false negative |   | in table sideways
1257 | Dendrocolaptes picumnus picumnus | false negative |   | in table sideways
1257 | Epinecrophylla gutturalis | false negative |   | in table sideways
1257 | Epinecrophylla haematonota | false negative |   | in table sideways
1257 | Euphonia cayennensis | false negative |   | in table sideways
1257 | Frederickena unduligera | false negative |   | in table sideways
1257 | Frederickena viridis | false negative |   | in table sideways
1257 | G. a. chalcocephala | false negative |   | in table sideways
1257 | G. d. brunneiceps | false negative |   | in table sideways
1257 | G. s. rufigularis | false negative |   | in table sideways
1257 | G. v. cinereiceps | false negative |   | in table sideways
1257 | Galbula albirostris albirostris | false negative |   | in table sideways
1257 | Galbula dea dea | false negative |   | in table sideways
1257 | Glyphorynchus spirurus spirurus | false negative |   | in table sideways
1257 | Grallaria varia varia | false negative |   | in table sideways
1257 | Gymnopithys leucaspis | false negative |   | in table sideways
1257 | Gymnopithys rufigula | false negative |   | in table sideways
1257 | H. f. aurigularis | false negative |   | in table sideways
1257 | H. o. ferrugineifrons | false negative |   | in table sideways
1257 | H. z. zosterops | false negative |   | in table sideways
1257 | Hemithraupis flavicollis flavicollis | false negative |   | in table sideways
1257 | Hemitriccus zosterops rothschildi | false negative |   | in table sideways
1257 | Hylophilus muscicapinus | false negative |   | in table sideways
1257 | Hylophilus ochraceiceps luteifrons | false negative |   | in table sideways
1257 | Hypocnemis cantator | false negative |   | in table sideways
1257 | Hypocnemis flavescens | false negative |   | in table sideways
1257 | Iodopleura fusca | false negative |   | in table sideways
1257 | Iodopleura isabellae | false negative |   | in table sideways
1257 | Lepidocolaptes albolineatus albolineatus | false negative |   | in table sideways
1257 | Lepidothrix coronata | false negative |   | in table sideways
1257 | Lepidothrix serena | false negative |   | in table sideways
1257 | M. a. melaena | false negative |   | in table sideways
1257 | M. b. albigularis-caurensis | false negative |   | in table sideways
1257 | M. c. collaris | false negative |   | in table sideways
1257 | M. c. dissors | false negative |   | in table sideways
1257 | M. m. elegans | false negative |   | in table sideways
1257 | M. m. microstephanus | false negative |   | in table sideways
1257 | M. m. pallida | false negative |   | in table sideways
1257 | Microbates collaris torquatus | false negative |   | in table sideways
1257 | Microcerculus bambla bambla | false negative |   | in table sideways
1257 | Momotus momota momota | false negative |   | in table sideways
1257 | Monasa atra | false negative |   | in table sideways
1257 | Monasa morphoeus | false negative |   | in table sideways
1257 | Myrmoborus myotherinus ardesiacus | false negative |   | in table sideways
1257 | Myrmothera campanisona campanisona | false negative |   | in table sideways
1257 | Myrmotherula axillaris axillaris | false negative |   | in table sideways
1257 | Myrmotherula guttata | false negative |   | in table sideways
1257 | Myrmotherula hauxwelli | false negative |   | in table sideways
1257 | Myrmotherula menetriesii cinereiventris | false negative |   | in table sideways
1257 | Notharchus hyperrhynchus | false negative |   | in table sideways
1257 | Notharchus macrorhynchos | false negative |   | in table sideways
1257 | O. c. castelnaui | false negative |   | in table sideways
1257 | Onychorhynchus coronatus coronatus | false negative |   | in table sideways
1257 | P. a. peruvianus | false negative |   | in table sideways
1257 | P. c. coronatus | false negative |   | in table sideways
1257 | P. c. griseipectus | false negative |   | in table sideways
1257 | P. c. ochroptera-napensis | false negative |   | in table sideways
1257 | P. c. tschudii | false negative |   | in table sideways
1257 | P. f. magnus | false negative |   | in table sideways
1257 | P. g. facilis | false negative |   | in table sideways
1257 | P. r. minor | false negative |   | in table sideways
1257 | P. s. insolitus | false negative |   | in table sideways
1257 | Percnostola rufifrons rufifrons | false negative |   | in table sideways
1257 | Phaethornis superciliosus superciliosus | false negative |   | in table sideways
1257 | Pheugopedius coraya coraya | false negative |   | in table sideways
1257 | Phoenicircus carnifex | false negative |   | in table sideways
1257 | Phoenicircus nigricollis | false negative |   | in table sideways
1257 | Piculus flavigula flavigula | false negative |   | in table sideways
1257 | Piprites chloris chlorion | false negative |   | in table sideways
1257 | Platyrinchus coronatus gumia | false negative |   | in table sideways
1257 | Polioptila guianensis guianensis | false negative |   | in table sideways
1257 | Psophia crepitans crepitans | false negative |   | in table sideways
1257 | Pteroglossus aracari | false negative |   | in table sideways
1257 | Pteroglossus pluricinctus | false negative |   | in table sideways
1257 | Pyrilia barrabandi | false negative |   | in table sideways
1257 | Pyrilia caica | false negative |   | in table sideways
1257 | R. t. cuvieri | false negative |   | in table sideways
1257 | R. v. culminatus | false negative |   | in table sideways
1257 | Ramphastos tucanus tucanus | false negative |   | in table sideways
1257 | Ramphastos vitellinus vitellinus | false negative |   | in table sideways
1257 | S. g. amazonus | false negative |   | in table sideways
1257 | S. l. infuscata | false negative |   | in table sideways
1257 | S. r. confinis | false negative |   | in table sideways
1257 | S. t. amazonus | false negative |   | in table sideways
1257 | Schiffornis turdinus turdinus | false negative |   | in table sideways
1257 | Schistocichla leucostigma leucostigma | false negative |   | in table sideways
1257 | Selenidera nattereri | false negative |   | in table sideways
1257 | Selenidera piperivora | false negative |   | in table sideways
1257 | Sittasomus griseicapillus axillaris | false negative |   | in table sideways
1257 | Synallaxis rutilans dissors | false negative |   | in table sideways
1257 | T. a. cinereiceps | false negative |   | in table sideways
1257 | T. a. examinatus | false negative |   | in table sideways
1257 | T. e. venezuelensis | false negative |   | in table sideways
1257 | T. f. nigrofasciata | false negative |   | in table sideways
1257 | T. m. media | false negative |   | in table sideways
1257 | T. m. murinus | false negative |   | in table sideways
1257 | T. p. poliocephalus | false negative |   | in table sideways
1257 | T. r. sulphureus | false negative |   | in table sideways
1257 | T. s. brevipes | false negative |   | in table sideways
1257 | Tachyphonus surinamus surinamus | false negative |   | in table sideways
1257 | Tangara mexicana mexicana | false negative |   | in table sideways
1257 | Terenotriccus erythrurus erythrurus | false negative |   | in table sideways
1257 | Thalurania furcata furcata | false negative |   | in table sideways
1257 | Thamnophilus amazonicus divaricatus | false negative |   | in table sideways
1257 | Thamnophilus murinus cayennensis | false negative |   | in table sideways
1257 | Todirostrum chrysocrotaphum | false negative |   | in table sideways
1257 | Todirostrum pictum | false negative |   | in table sideways
1257 | Tolmomyias assimilis neglectus | false negative |   | in table sideways
1257 | Tolmomyias poliocephalus sclateri-klagesi | false negative |   | in table sideways
1257 | Topaza pella | false negative |   | in table sideways
1257 | Topaza pyra | false negative |   | in table sideways
1257 | Trogon rufus rufus | false negative |   | in table sideways
1257 | Tyranneutes stolzmanni | false negative |   | in table sideways
1257 | Tyranneutes virescens | false negative |   | in table sideways
1257 | Veniliornis affinis | false negative |   | in table sideways
1257 | Veniliornis cassini | false negative |   | in table sideways
1257 | W. p. duidae | false negative |   | in table sideways
1257 | Willisornis poecilinotus poecilinotus | false negative |   | in table sideways
1257 | X. g. guttatoides | false negative |   | in table sideways
1257 | X. m. remoratus | false negative |   | in table sideways
1257 | Xenops minutus ruficaudus | false negative |   | in table sideways
1257 | Xiphorhynchus ocellatus | false negative |   | in table sideways
1257 | Xiphorhynchus pardalotus | false negative |   | in table sideways
1257 | Zimmerius acer | false negative |   | in table sideways
1257 | Zimmerius gracilipes | false negative |   | in table sideways
1332 | Eleutherodactylini | false negative |   | in table sideways
487 | Derelominae | false negative |   | in table sideways and line break
536 | A. californica obscura | false negative |   | in table sideways on multiple lines
536 | A. californica caurina | false negative |   | in table sideways on multiple lines
536 | A. californica woodhouseii | false positive |   | in table sideways on multiple lines
536 | A. californica texana | false positive |   | in table sideways on multiple lines
536 | A. unicolor guerrerensis | false positive |   | in table sideways on multiple lines
536 | A. californica sumichrasti | false positive |   | in table sideways on multiple lines
536 | A. californica cyanotis | false positive |   | in table sideways on multiple lines
536 | A. californica grisea | false positive |   | in table sideways on multiple lines
297 | Lemuriformes | false negative |   | in table with slash
346 | Sphyrna probatocephalus tiburo | false positive |   | maybe a jumble of two names in a table
346 | Haemulon saurus plumieri | false positive |   | maybe a jumble of two names in a table
438 | Picture-winged planitibia grimshawi | false positive |   | messed up lines in a table
346 | Archosargus | false positive |   | never occurs alone, but does occur on one   line in table
346 | Negaprion | false positive |   | never occurs alone, but does occur on one line in table
346 | Xenacanthus | false positive |   | never occurs alone, but does occur on one line in text and table
258 | Nelumbo | false negative |   | occurs in table and separated from other   names with slash
258 | Cocoloba | false negative |   | occurs in table and separated from other names with slash
258 | Phytolacca | false negative |   | occurs in table and separated from other names with slash
258 | Capparis | false negative |   | occurs in table and separated from other names with slash
258 | Placospermum | false negative |   | occurs in table and separated from other names with slash
258 | Campanula | false negative |   | occurs in table and separated from other names with slash
258 | Abobra | false negative |   | occurs in table and separated from other names with slash
258 | Decaisnea | false negative |   | occurs in table and separated from other names with slash
258 | Aucuba | false negative |   | occurs in table and separated from other names with slash
258 | Eucommia | false negative |   | occurs in table and separated from other names with slash
258 | Lobelia | false negative |   | occurs in table and separated from other names with slash
258 | Poncirus | false negative |   | occurs in table and separated from other names with slash
258 | Platanus | false negative |   | occurs in table and separated from other names with slash
258 | Datisca | false negative |   | occurs in table and separated from other names with slash
258 | Hydrastis | false negative |   | occurs in table and separated from other names with slash
258 | Penthorum | false negative |   | occurs in table and separated from other names with slash
258 | Illiciales | false negative |   | occurs in table and separated from other names with slash
258 | Sinofranchetia | false negative |   | occurs in table and separated from other names with slash
258 | Roussea | false negative |   | occurs in table and separated from other names with slash
258 | Nandina | false negative |   | occurs in table and separated from other names with slash
258 | Citrus | false negative |   | occurs in table and separated from other names with slash
258 | Sedum | false negative |   | occurs in table and separated from other names with slash
258 | Chloranthus | false negative |   | occurs in table and separated from other names with slash
258 | Ranunculus | false negative |   | occurs in table and separated from other names with slash
258 | Nepenthes | false negative |   | occurs in table and separated from other names with slash
258 | Phacelia | false negative |   | occurs in table and separated from other names with slash
258 | Humulus | false negative |   | occurs in table and separated from other names with slash
258 | Glaucidium | false negative |   | occurs in table and separated from other names with slash
258 | Akebia | false negative |   | occurs in table and separated from other names with slash
258 | Urtica | false negative |   | occurs in table and separated from other names with slash
258 | Bourreria | false negative |   | occurs in table and separated from other names with slash
258 | Garrya | false negative |   | occurs in table and separated from other names with slash
258 | Hydrophyllum | false negative |   | occurs in table and separated from other names with slash
258 | Tetracarpaea | false negative |   | occurs in table and separated from other names with slash
258 | Asarum | false negative |   | occurs in table and separated from other names with slash
258 | Kalenchoe | false negative |   | occurs in table and separated from other names with slash
258 | Morus | false negative |   | occurs in table and separated from other names with slash
258 | Saruma | false negative |   | occurs in table and separated from other names with slash
258 | Coriaria | false negative |   | occurs in table and separated from other names with slash
258 | Piperaceae | false negative |   | occurs in table and separated from other names with slash
258 | Plumbago | false negative |   | occurs in table and separated from other names with slash
258 | Ceanothus | false negative |   | occurs in table and separated from other names with slash
258 | Brassica | false negative |   | occurs in table and separated from other names with slash
258 | Floerkea | false negative |   | occurs in table and separated from other names with slash
258 | Saururaceae | false negative |   | occurs in table and separated from other names with slash
258 | Dudleya | false negative |   | occurs in table and separated from other names with slash
258 | Mirabilis | false negative |   | occurs in table and separated from other names with slash
258 | Ailanthus | false negative |   | occurs in table and separated from other names with slash
258 | Austrobaileya | false negative |   | occurs in table and separated from other names with slash
258 | Haloragis | false negative |   | occurs in table and separated from other names with slash
258 | Tetragonia | false negative |   | occurs in table and separated from other names with slash
422 | Nov. flaviventris caligata | false positive |   | possibly a problem with line breaks in a   table
422 | Marmota monax marmota | false positive |   | possibly a problem with line breaks in a table
457 | Agathaphaga | false negative |   | table sideways
346 | Callinectes | false positive |   | genus that does not occur alone, but does   occur on two lines in a table
1326 | Cheimerius | false positive |   | never appears as lone genus - linebreak in   table
1326 | Chrysoblephus | false positive |   | never appears as lone genus - linebreak in table
1326 | Pagellus | false positive |   | never appears as lone genus - linebreak in table
1326 | Rhabdosargus | false positive |   | never appears as lone genus - linebreak in table
1326 | Pachymetopon | false positive |   | never appears as lone genus - linebreak in table
1326 | Polysteganus | false positive |   | never appears as lone genus - linebreak in table
1326 | Acanthopagrus | false positive |   | never appears as lone genus - linebreak in table
1326 | Diplodus cervinus | false positive |   | never appears without subspecies -   linebreak in table

**Comment by dimus** [comment]
I am not sure what can be done here. As I understand it is a text-conversion issue, so results depend on the quality of  poppler software :-/

**Comment by diatomsRcool** [comment]
I will look at the text files to see what the conversion looks like. For the paper, do you think we should find a way to get the tables converted properly so we can do an honest estimate of GNRD's ability? I worry if we just throw these out we may not have enough data for testing.

**Comment by dimus** [comment]
Do you mean conveting them to text with something like Acrobat reader?

**Comment by diatomsRcool** [comment]
I'm not sure what the final answer would be. Spot checking suggests its reading the words just fine, its just not putting them in the right place. When a binomial occurs on two different lines the words are getting jumbled and binomials are being broken up. When a name is presented with a slash "/" GNRD is not finding it even if it does get represented correctly in the text file.
So addressing the / issue would help, but I'm not sure what to do about the table line break issue.
