### ISSUE TITLE
GNRD is identifying adjectives as taxon names

### ISSUE THREAD

**Issue by diatomsRcool** [GlobalNamesArchitecture/gnrd#37]
Data package ID | name | error type | text string | notes
-- | -- | -- | -- | --
1005 | Australasian | false positive |   | adjective
1054 | Apicomplexan | false positive |   | adjective
1457 | Tasmanian | false positive |   | adjective
1463 | Tasmanian | false positive |   | adjective and part of common name
457 | Australasian | false positive |   | adjective describing distribution
186 | Coriscium-type thalli | false positive |   | genus used as a descriptor

**Comment by dimus** [comment]
That happens as a result of http://verifier.globalnames.org/api/v1/verifications/Australian

I am hunting for adjectives and putting them to reject list, thanks for finding these, they will be added
