### ISSUE TITLE
Canonical name at terminal end of content (& no punctuation) not recognized

### ISSUE THREAD

**Issue by dshorthouse** [GlobalNamesArchitecture/gnrd#4]
Example:
There is a spider called Pardosa moesta
vs:
There is a spider called Pardosa moesta.

Note the period in the second & not in the first. Only the second results in name "Pardosa moesta" being recognized.

**Comment by dimus** [comment]
It is a problem with name-spotter gem, It is patched there, so GNRD finds the names in the very end of the text now. I do have to do something with the code though, as it won't pass tests on newer versions of Linux. Probably heavysh refactoring is in order
