### ISSUE TITLE
GNRD missing virus names

### ISSUE THREAD

**Issue by diatomsRcool** [GlobalNamesArchitecture/gnrd#45]
Not sure if this is in scope

Data package ID | name | error type | text string | notes
-- | -- | -- | -- | --
350 | hantavirus | false negative |   | maybe GNRD isn't meant to handle virus   names
350 | Calabazo hantavirus | false negative |   | maybe GNRD isn't meant to handle virus names
350 | Sin Nombre hantavirus | false negative | prevalence of Sin Nombre and Calabazo   hantaviruses | name is broken up, but not sure this is a   real name
385 | human immunovirus | false negative |   | virus name
1191 | cloudy wing virus | false negative |   | virus name
1191 | black queen cell virus | false negative |   | virus name
1191 | deformed wing virus | false negative |   | virus name
1191 | slow paralysis virus | false negative |   | virus name
1191 | acute bee paralysis virus | false negative |   | virus name
1191 | Kashmir bee virus | false negative |   | virus name
385 | Pestivirus | false negative |   | virus name - in table

**Comment by dimus** [comment]
Yes, viruses are not supported yet, and not sure when they will be. I do not see clear path how to normalize their names, parse them and find them in the text.
