### ISSUE TITLE
Two names hyphenated together

### ISSUE THREAD

**Issue by diatomsRcool** [GlobalNamesArchitecture/gnrd#47]
GNRD finds the text string, but doesn't know what to do with it. It can't see that it is two names hyphenated together.

Data package ID | name | error type | text string | notes
-- | -- | -- | -- | --
1044 | N. giraulti | false negative | N. giraulti-Nasonia longicornis | punctuation
1044 | Nasonia longicornis | false negative | N. giraulti-Nasonia longicornis | punctuation

**Comment by dimus** [comment]
for this to work we would need to consider a hyphen as a possible space. It would create much more false positives than false negatives, so such construction fails.
