### ISSUE TITLE
hyphens get returned as an odd character

### ISSUE THREAD

**Issue by diatomsRcool** [GlobalNamesArchitecture/gnrd#48]
For example, in the JSON for data package 1044, GNRD finds the string verbatim: "N. giraulti-Nasonia longicornis" but lists name: "N. giraulti?nasonia longicornis". How can we get the hyphen in verbatim to show up in name?

**Comment by dimus** [comment]
OCR puts all kind of weird characters inside of the names, so if gnfinder encounters them it substitutes all of them with �, however hythen should be allowed. I'll try to figure out what is going on here.
