### ISSUE TITLE
GNRD having hard time reconciling abbreviated names

### ISSUE THREAD

**Issue by diatomsRcool** [GlobalNamesArchitecture/gnrd#50]
I have not done an exhaustive search, but via spot checking, I'm having a hard time finding an example of an abbreviated name being matched. Examples are below. All have "noMatch" matchType - even if the full name is also given in the text.

Data package ID | name
--|--
39 | N. nebulosa
18 | O. dioica
29 | A. arundinaceus

**Comment by dimus** [comment]
Names like these are not supported by matching algorithms yet because of false positives, but it is planned for the future.
