### ISSUE TITLE
GNRD misses "Bacteria"

### ISSUE THREAD

**Issue by diatomsRcool** [GlobalNamesArchitecture/gnrd#52]
Technically, Bacteria is the name of a Domain of life, like Eukaryota and Archaea, but it is often used as a common name, bacteria. I'm not sure how you want to handle this. When calculating performance, I take all lower case bacteria as a common name and all uppercase Bacteria as a taxon name. As a result "Bacteria" is labeled as a false negative. Would you like to say that all instances of Bacteria are also common names?

**Comment by dimus** [comment]
Bacteria can be used as vernacular and scientific name, so it is in a grey dictionary. Names like these wont be found because of a huge number of false positives. We will take care of such names when we get context analysis working.
