### ISSUE TITLE
Internal server error on docker container

### ISSUE THREAD

**Issue by darwinzer0** [GlobalNamesArchitecture/gnrd#9]
I am trying to install the docker container to run GNRD locally.  I ran `docker pull gnames/gnrd`, then started the container with this command to forward port 80 in the container to 5678 on my machine:

`docker run -p 5678:80 gnames/gnrd`

It seems to load up no problems, and I can load static pages like 0.0.0.0:5678/api, but when I try to connect to the API using a command like the following, then I just get <h1>Internal Server Error</h1> as a response.

`curl -L http://0.0.0.0:5678/name_finder.json?url=http://en.wikipedia.org/wiki/Araneae`

Any suggestions on what I might be doing wrong?

**Comment by dimus** [comment]
Did you install TaxonFinder, NetiNeti and Postgres docker containers as well? What I would recommend is to follow https://github.com/GlobalNamesArchitecture/gnrd#install-for-production-on-one-machine

**Comment by darwinzer0** [comment]
Thanks, that helped to go through the steps there.  I'm using Amazon Linux, which for some reason has only docker 1.9 in their repo, and you need 1.10 to use the most recent docker-compose with the new configuration file format.  So I ended up going through the compose process manually, and that worked.
